name: "deploy"
description: "deploy action"
inputs:
  CLIENT_ID:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout current commit
      uses: actions/checkout@v4

    - name: Log client id
      shell: bash
      run: |
        echo "Client id is ${{inputs.CLIENT_ID}}"  

    - name: Extract secret
      shell: bash
      run: |
        CF_DIST_ID=${{ secrets[format('{0}_CF_DIST_ID', inputs.CLIENT_ID)] }}
        echo "CF_DIST_ID:: ${{CF_DIST_ID}} or $CF_DIST_ID"
        S3_BUCKET=${{ secrets[format('{0}_S3_BUCKET', inputs.CLIENT_ID)] }}
        echo ":S3_BUCKET: ${{S3_BUCKET}} or $S3_BUCKET"  


    - uses: actions/download-artifact@v4
      with:
        name: "fstandard-artifact"
        path: dist

    - name: Setup Python 3.7 for awscli
      uses: actions/setup-python@v4
      with:
        version: "3.7"
        architecture: "x64"     

    - name: Install awscli
      shell: bash
      run: pip install --upgrade pip awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_IAM_ROLE }}
        aws-region: ap-northeast-1

    - name: Deploy static site to S3 bucket
      shell: bash
      run: |
        aws s3 sync --delete dist ${{inputs.S3_BUCKET}} --cache-control max-age=60,s-maxage=60

    - name: Delete cf cache
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id ${{inputs.CF_DIST_ID}} --paths "/*"



