name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  BUILD_MODE: "dev"

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_ID: ${{ steps.extract_clientId.outputs.CLIENT_ID }}
      CF_DIST_ID: ${{ steps.extract_variable.outputs.CF_DIST_ID }}
      S3_BUCKET: ${{ steps.extract_variable.outputs.S3_BUCKET }}
      CLIENT_ID_UPPERCASE: ${{ steps.extract_clientId.outputs.CLIENT_ID_UPPERCASE }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - run: |
          echo "Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"

      - id: extract_clientId
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPERCASE=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "CLIENT_ID_UPPERCASE=$CLIENT_ID_UPPERCASE" >> "$GITHUB_ENV"
          echo "CLIENT_ID=$CLIENT_ID" >> "$GITHUB_OUTPUT"

      - id: extract_variable
        run: |
          CF_DIST_ID=${{ vars[format('{0}_CF_DIST_ID', env.CLIENT_ID_UPPERCASE)] }}
          echo "CF_DIST_ID=$CF_DIST_ID" >> "$GITHUB_OUTPUT"
          S3_BUCKET=${{ vars[format('{0}_S3_BUCKET', env.CLIENT_ID_UPPERCASE)] }}
          echo "S3_BUCKET=$S3_BUCKET" >> "$GITHUB_OUTPUT"

  build:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build
        with:
          CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}

  deploy:
    needs: [prebuild, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/deploy
        with:
          CF_DIST_ID: ${{needs.prebuild.outputs.CF_DIST_ID}}
          S3_BUCKET: ${{needs.prebuild.outputs.S3_BUCKET}}
          CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID_UPPERCASE}}
