name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_ID: ${{ steps.step1.outputs.CLIENT_ID }}
      CF_DIST_ID: ${{ steps.step2.outputs.CF_DIST_ID }}
      S3_BUCKET: ${{ steps.step2.outputs.S3_BUCKET }}
      TEST: "LALALA"

    steps:
      - id: step1
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_ENV"
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_OUTPUT"

      - id: step2
        run: |
          CF_DIST_ID=${{ secrets[format('{0}_CF_DIST_ID', env.CLIENT_ID)] }}
          echo "CF_DIST_ID=$CF_DIST_ID" >> "$GITHUB_OUTPUT"
          S3_BUCKET=${{ secrets[format('{0}_S3_BUCKET', env.CLIENT_ID)] }}
          echo "S3_BUCKET=$S3_BUCKET" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - name: Log env
        run: |
          echo "S3 bucket ${{needs.prebuild.outputs.S3_BUCKET}} "
          echo "CF DIST ${{needs.prebuild.outputs.CF_DIST_ID}} "
          echo "check  ${{needs.prebuild.outputs.TEST}} "
      # - env:
      #   OUTPUT1: ${{needs.prebuild.outputs.CLIENT_ID}}
      #   OUTPUT2: ${{needs.prebuild.outputs.output2}}
      #   run: echo "$OUTPUT1 $OUTPUT2"


  # build:
  #   needs: [job1]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Check env CLIENT_ID
  #       run: echo "The value of CLIENT_ID is ${{ needs.job1.outputs.CLIENT_ID }} and output1 is ${{ needs.job1.outputs.output1 }}"       

  #     - uses: ./.github/actions/build
  #       with:
  #         CLIENT_ID: ${{ needs.job1.outputs.CLIENT_ID }}

  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Check env CF_DIST_ID and S3_BUCKET
  #       run: echo "The value of CF_DIST_ID is ${{ needs.job1.outputs.CF_DIST_ID }} and S3_BUCKET is ${{ needs.job1.outputs.S3_BUCKET }}"

  #     - uses: ./.github/actions/deploy
  #       with:
  #         CF_DIST_ID: ${{ needs.job1.outputs.CF_DIST_ID }}
  #         S3_BUCKET: ${{ needs.job1.outputs.S3_BUCKET }}
