name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_ID: ${{ steps.extract_client.outputs.CLIENT_ID }}
      CF_DIST_ID: ${{ steps.extract_variable.outputs.CF_DIST_ID }}
      S3_BUCKET: ${{ steps.extract_variable.outputs.S3_BUCKET }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract client from tag
        id: extract_client
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_OUTPUT"
  
      - name: Extract variable from tag
        id: extract_variable
        run: |
          CF_DIST_ID=${{ vars[format('{0}_CF_DIST_ID', env.CLIENT_ID)] }}
          echo "CF_DIST_ID=$CF_DIST_ID" >> "$GITHUB_OUTPUT"
          S3_BUCKET=${{ vars[format('{0}_S3_BUCKET', env.CLIENT_ID)] }}
          echo "S3_BUCKET=$S3_BUCKET" >> "$GITHUB_OUTPUT"

  build:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build
        with:
          CLIENT_ID: ${{ needs.prebuild.outputs.CLIENT_ID }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log variable from env
        run: |
          echo "Log variable CF_DIST_ID is ${{ needs.prebuild.outputs.CF_DIST_ID }}"
          echo "Log variable S3_BUCKET is ${{ needs.prebuild.outputs.S3_BUCKET }}"
           
      - uses: ./.github/actions/deploy
        with:
          CF_DIST_ID: ${{ needs.prebuild.outputs.CF_DIST_ID }}
          S3_BUCKET: ${{ needs.prebuild.outputs.S3_BUCKET }}
