name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  AWS_IAM: 583388259455
  AWS_DEFAULT_REGION: ap-southeast-1


jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_ID: ${{ steps.extract_clientId.outputs.CLIENT_ID }}
      CF_DIST_ID: ${{ steps.extractDeployEnv.outputs.CF_DIST_ID }}
      S3_BUCKET: ${{ steps.extractDeployEnv.outputs.S3_BUCKET }}
    steps:
      - id: extract_clientId
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_OUTPUT"
          echo "CLIENT_ID_UPPER=$CLIENT_ID_UPPER" >> "$GITHUB_ENV"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_IAM }}:role/test-get-secrets
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Get secrets from AWS Secrets Manager
        run: |
          SECRETS=$(aws secretsmanager get-secret-value --secret-id multiTenantEnv --query SecretString --output text)
          echo "$SECRETS" | jq .
          echo "$SECRETS" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - id: extractDeployEnv
        run: |
          CF_DIST_ID=${{ env[format('{0}_CF_DIST_ID', env.CLIENT_ID_UPPER)] }}
          echo "CF_DIST_ID=$CF_DIST_ID" >> "$GITHUB_OUTPUT"
          S3_BUCKET=${{ env[format('{0}_S3_BUCKET', env.CLIENT_ID_UPPER)] }}
          echo "S3_BUCKET=$S3_BUCKET" >> "$GITHUB_OUTPUT"

  build:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - uses: ./.github/actions/build
        with:
          CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}

  deploy:
    needs: [prebuild, build]
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - uses: ./.github/actions/deploy
        with:
          CF_DIST_ID: ${{needs.prebuild.outputs.CF_DIST_ID}}
          S3_BUCKET: ${{needs.prebuild.outputs.S3_BUCKET}}



