name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  AWS_IAM: 583388259455
  AWS_DEFAULT_REGION: us-east-1


jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_ID: ${{ steps.extract_clientId.outputs.CLIENT_ID }}
    steps:
      - id: extract_clientId
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_OUTPUT"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_IAM }}:role/test-cicd-pnpm
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Get secrets from AWS Secrets Manager
        run: |
          SECRETS=$(aws secretsmanager get-secret-value --secret-id FAA-dev-secret --query SecretString --output text)
          echo "$SECRETS" | jq .

  build:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - uses: ./.github/actions/build
        with:
          CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}

  deploy:
    needs: [prebuild, build]
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract secret
        run: |
            CF_DIST_ID=${{ secrets[format('{0}_CF_DIST_ID', env.CLIENT_ID)] }}
            S3_BUCKET=${{ secrets[format('{0}_S3_BUCKET', env.CLIENT_ID)] }}
            echo "CF_DIST_ID=$CF_DIST_ID" >> $GITHUB_ENV
            echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
            
      - uses: ./.github/actions/deploy
        with:
          CF_DIST_ID: ${{env.CF_DIST_ID}}
          S3_BUCKET: ${{env.S3_BUCKET}}



