name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.extractCF.outputs.test }}
      output3: ${{ steps.extractS3.outputs.test }}
    steps:
      - id: step1
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "test=$CLIENT_ID_UPPER" >> "$GITHUB_OUTPUT"
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_ENV"

      - name: Extract CF_DIST_ID from tag
        id: extractCF
        run: |
          echo "kaslfkl;asfkl;asfkl; ${{format('{0}_CF_DIST_ID', env.CLIENT_ID)}}"
          CF_DIST_ID=${{ vars[format('{0}_CF_DIST_ID', env.CLIENT_ID)] }}
          echo "test=$CF_DIST_ID" >> "$GITHUB_OUTPUT"

      - name: Extract S3 from tag
        id: extractS3
        run: |
            S3_BUCKET=${{ vars[format('{0}_S3_BUCKET', env.CLIENT_ID)] }}
            echo "test=$S3_BUCKET" >> "$GITHUB_OUTPUT"
  

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: log env
        run: echo "output is ${{needs.job1.outputs.output1}}  ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}"



  # prebuild:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Extract client from tag
  #       id: extract_client
  #       run: |
  #         TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
  #         CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
  #         CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
  #         echo "CLIENT_ID=$CLIENT_ID_UPPER" >> $GITHUB_ENV
  
  #     - name: Extract variable from tag
  #       id: extract_variable
  #       run: |
  #         CF_DIST_ID=${{ vars[format('{0}_CF_DIST_ID', env.CLIENT_ID)] }}
  #         echo "CF_DIST_ID=$CF_DIST_ID" >> $GITHUB_ENV
  #         S3_BUCKET=${{ vars[format('{0}_S3_BUCKET', env.CLIENT_ID)] }}
  #         echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV

  # build:
  #   needs: [prebuild]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/build
  #       with:
  #         CLIENT_ID: $CLIENT_ID

  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Access environment variable
  #       run: echo "The value of MY_ENV_VAR is $GITHUB_ENV and $S3_BUCKET"
           
  #     - uses: ./.github/actions/deploy
  #       with:
  #         CF_DIST_ID: $CF_DIST_ID
  #         S3_BUCKET: $S3_BUCKET
