name: deploy-DEV

on:
  push:
    tags:
      - dev-*-*

permissions:
  id-token: write
  contents: read

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  FSTANDARD_CF_DIST_ID: 'E180JSU5L1WAE9'
  FSTANDARD_S3_BUCKET: 's3://s3-cicd-github-bucket'
  FINATEXTHD_CF_DIST_ID: 'E11F5KND1G7976'
  FINATEXTHD_S3_BUCKET: 's3://s3-bucket-tenant-2'

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_ID: ${{ steps.extract_clientId.outputs.CLIENT_ID }}
    steps:
      - id: extract_clientId
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/dev-||')
          CLIENT_ID=$(echo $TAG_NAME | sed 's|-.*||')
          CLIENT_ID_UPPER=$(echo $CLIENT_ID | tr '[:lower:]' '[:upper:]')
          echo "CLIENT_ID=$CLIENT_ID_UPPER" >> "$GITHUB_OUTPUT"
  
  build:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - uses: ./.github/actions/build
        with:
          CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}

  deploy:
    needs: [prebuild, build]
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{needs.prebuild.outputs.CLIENT_ID}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/deploy
        with:
          CF_DIST_ID: ${{env.CF_DIST_ID}}
          S3_BUCKET: ${{env.S3_BUCKET}}

