name: deploy-DEV

on:
  push:
    tags:
      - dev-*

permissions:
  id-token: write
  contents: read

env:
  CF_DIST_ID: 'E180JSU5L1WAE9'
  S3_BUCKET: 's3://s3-cicd-github-bucket'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/deploy